# Generated by Django 4.2.20 on 2025-03-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidbook_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_class',
            field=models.CharField(default='color-teal', max_length=50, verbose_name='CSS-класс цвета'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='item_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество записей'),
        ),
    ]
