# Generated by Django 4.2.20 on 2025-03-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidbook_app', '0003_record_short_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
