# Generated by Django 4.2.20 on 2025-03-27 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidbook_app', '0004_tag_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='short_content',
            field=models.TextField(verbose_name='Краткое содержание записи (HTML)'),
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Текстовый блок'), ('image', 'Фото блок'), ('video', 'Видео блок')], max_length=50, verbose_name='Тип блока')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание/Содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='guidbook_app.record', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
                'ordering': ['order'],
            },
        ),
    ]
