# Generated by Django 4.2.20 on 2025-03-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidbook_app', '0005_alter_record_short_content_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='list_items',
            field=models.JSONField(blank=True, null=True, verbose_name='Элементы списка'),
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('text', 'Текстовый блок'), ('image', 'Фото блок'), ('video', 'Видео блок'), ('list', 'Список')], max_length=50, verbose_name='Тип блока'),
        ),
    ]
