# Generated by Django 4.2.20 on 2025-03-27 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidbook_app', '0006_block_list_items_alter_block_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='list_items',
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('text', 'Текстовый блок'), ('image', 'Фото блок'), ('video', 'Видео блок')], max_length=50, verbose_name='Тип блока'),
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='guidbook_app.block')),
            ],
        ),
    ]
