# Generated by Django 4.2.20 on 2025-04-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidbook_app', '0007_remove_block_list_items_alter_block_type_listitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('text', 'Текстовый блок'), ('image', 'Фото блок'), ('video', 'Видео блок'), ('file', 'Файловый блок')], max_length=50, verbose_name='Тип блока'),
        ),
        migrations.DeleteModel(
            name='ListItem',
        ),
    ]
