# Generated by Django 4.2.20 on 2025-04-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidbook_app', '0008_block_file_alter_block_type_delete_listitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=200, verbose_name='Факультет')),
                ('course', models.CharField(max_length=100, verbose_name='Курс')),
                ('subject', models.CharField(max_length=200, verbose_name='Предмет')),
                ('work_type', models.CharField(max_length=100, verbose_name='Тип работы')),
                ('student_name', models.CharField(max_length=200, verbose_name='ФИО студента')),
                ('contact_info', models.CharField(max_length=200, verbose_name='Контактные данные')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запрос студента',
                'verbose_name_plural': 'Запросы студентов',
            },
        ),
    ]
