# Generated by Django 4.2.20 on 2025-04-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidbook_app', '0010_studentrequest_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrequest',
            name='file',
            field=models.FileField(upload_to='student_requests/', verbose_name='Прикрепленный файл'),
        ),
    ]
