# Базовый образ Python
FROM python:3.9-slim

# Установка рабочей директории внутри контейнера
WORKDIR /app

# Копирование файлов зависимостей
COPY requirements.txt .

# Установка зависимостей
RUN pip install --no-cache-dir -r requirements.txt

# Копирование остальных файлов проекта
COPY . .

# Порт, на котором будет работать Django
EXPOSE 8010

# Команда для запуска сервера разработки
CMD ["python", "manage.py", "runserver", "0.0.0.0:8010"]